# Front/Dockerfile

# Etapa 1: build de la app
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: servir estáticos con nginx
FROM nginx:alpine

# Copiamos el build al directorio que sirve nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Exponemos el puerto del servidor web
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
